### ISSUE TITLE
Code generation: default services in ServiceRegistry are erased

### ISSUE THREAD

**Issue by ludovicc** [KyleU/databaseflow#2]
Hello,

The code generation remove the first 3 lines in class ServiceRegistry (app/services/ServiceRegistry.scala)
causing compilation issues.

**Comment by KyleU** [comment]
A lot of codegen depends (for now) on those tables being present. Start Boilerplay pointed to your database and they'll be automatically created (and therefore included in the export). I'll update the documentation, thanks for the report
