### ISSUE TITLE
Too many open cursors

### ISSUE THREAD

**Issue by rich-coe** [KyleU/databaseflow#5]
- configure db connection
- open db connection
- errors of the form 
    [info] 09:59:03.421 s.MetadataProcedures: Unable to get procedure details for [ANY_TABLE_NAME].
java.sql.SQLException: ORA-01000: maximum open cursors exceeded

querying the db as sysdba shows 300 open cursors

**Comment by KyleU** [comment]
Ooh, yeah, I pull metadata in parallel. It shouldn't be 300 cursors though, I thought it capped at the size of the executing pool, in this case 2x core count. I have to admit I haven't done much testing with Oracle. I don't suppose you could share your schema or provide a server I can connect to?

**Comment by rich-coe** [comment]
I've yet to build from source to debug this.  The DB is not publicly available on the internet.
I don't think there's anything remarkable about the DB schema I'm using.

**Comment by KyleU** [comment]
I've upgraded the connection pool, and verified that the number of active connections is limited to one for metadata pulls. I've done very little testing with Oracle, sure hope this fixes it...
